**DYNAMIC PRICING INTELLIGENCE**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

loaded dataset

In [ ]:
products=pd.read_csv("/products.csv")
prices=pd.read_csv("/competitor_prices.csv")
sales=pd.read_csv("/sales.csv")

EDA-exploitary data analysis

In [5]:
products=pd.read_csv("/products.csv")
products.head()

  product_id      product_name   category       brand
0       P001  Household Item 1  Household  Surf Excel
1       P002    Grocery Item 2    Grocery         ABC
2       P003    Grocery Item 3    Grocery         ABC
3       P004  Household Item 4  Household  Surf Excel
4       P005     Snacks Item 5     Snacks        Lays

In [6]:
prices=pd.read_csv("/competitor_prices.csv")
prices.head()

         date product_id   platform   price  discount  stock_status
0  2026-01-01       P001     Amazon  495.29        20      In Stock
1  2026-01-01       P002   Flipkart  358.08         0      In Stock
2  2026-01-01       P003    Blinkit  419.81        10  Out of Stock
3  2026-01-01       P004  BigBasket  170.48         5  Out of Stock
4  2026-01-02       P005     Amazon  145.68        15  Out of Stock

In [7]:
sales=pd.read_csv("/sales.csv")
sales.head()

  sale_id        date product_id  quantity  selling_price
0    S001  2026-01-01       P085         4         229.31
1    S002  2026-01-09       P009         5         208.02
2    S003  2026-01-17       P052         6         472.66
3    S004  2026-01-04       P034         3         311.27
4    S005  2026-01-09       P005         2         318.46

shapes of the row and coloum

In [8]:
products=pd.read_csv("/products.csv")
prices=pd.read_csv("/competitor_prices.csv")
sales=pd.read_csv("/sales.csv")
products.shape,prices.shape,sales.shape

((100, 4), (100, 6), (100, 5))

coloum name for each index

In [9]:
products=pd.read_csv("/products.csv")
prices=pd.read_csv("/competitor_prices.csv")
sales=pd.read_csv("/sales.csv")
products.columns,prices.columns,sales.columns

(Index(['product_id', 'product_name', 'category', 'brand'], dtype='object'),
 Index(['date', 'product_id', 'platform', 'price', 'discount', 'stock_status'], dtype='object'),
 Index(['sale_id', 'date', 'product_id', 'quantity', 'selling_price'], dtype='object'))

info()

In [10]:
products=pd.read_csv("/products.csv")
prices=pd.read_csv("/competitor_prices.csv")
sales=pd.read_csv("/sales.csv")
products.info(),prices.info(),sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    100 non-null    object
 1   product_name  100 non-null    object
 2   category      100 non-null    object
 3   brand         100 non-null    object
dtypes: object(4)
memory usage: 3.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          100 non-null    object
 1   product_id    100 non-null    object
 2   platform      100 non-null    object
 3   price         100 non-null    float64
 4   discount      100 non-null    int64
 5   stock_status  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   sale_id        100 non-null    object
 1   date           100 non-null    object
 2   product_id     100 non-null    object
 3   quantity       100 non-null    int64
 4   selling_price  100 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 4.0+ KB

(None, None, None)

In [12]:
products=pd.read_csv("/products.csv")
prices=pd.read_csv("/competitor_prices.csv")
sales=pd.read_csv("/sales.csv")
products.dtypes,prices.dtypes,sales.dtypes

(product_id      object
 product_name    object
 category        object
 brand           object
 dtype: object,
 date             object
 product_id       object
 platform         object
 price           float64
 discount          int64
 stock_status     object
 dtype: object,
 sale_id           object
 date              object
 product_id        object
 quantity           int64
 selling_price    float64
 dtype: object)

Describe()

In [15]:
products=pd.read_csv("/products.csv")
prices=pd.read_csv("/competitor_prices.csv")
sales=pd.read_csv("/sales.csv")
products.describe(include="all")

       product_id      product_name   category       brand
count         100               100        100         100
unique        100               100          6           6
top          P001  Household Item 1  Household  Surf Excel
freq            1                 1         20          20

In [16]:
products=pd.read_csv("/products.csv")
prices=pd.read_csv("/competitor_prices.csv")
sales=pd.read_csv("/sales.csv")
prices.describe(include="all")

              date product_id platform       price    discount stock_status
count          100        100      100  100.000000  100.000000          100
unique          25        100        4         NaN         NaN            2
top     2026-01-01       P001   Amazon         NaN         NaN     In Stock
freq             4          1       25         NaN         NaN           53
mean           NaN        NaN      NaN  268.234200   10.150000          NaN
std            NaN        NaN      NaN  138.691062    7.536276          NaN
min            NaN        NaN      NaN   51.460000    0.000000          NaN
25%            NaN        NaN      NaN  143.350000    5.000000          NaN
50%            NaN        NaN      NaN  251.690000   10.000000          NaN
75%            NaN        NaN      NaN  386.267500   16.250000          NaN
max            NaN        NaN      NaN  495.290000   20.000000          NaN

In [18]:
products=pd.read_csv("/products.csv")
prices=pd.read_csv("/competitor_prices.csv")
sales=pd.read_csv("/sales.csv")
sales.describe(include="all")

       sale_id        date product_id    quantity  selling_price
count      100         100        100  100.000000     100.000000
unique     100          24         65         NaN            NaN
top       S001  2026-01-15       P086         NaN            NaN
freq         1           8          4         NaN            NaN
mean       NaN         NaN        NaN    4.430000     282.719800
std        NaN         NaN        NaN    2.239476     119.982725
min        NaN         NaN        NaN    1.000000      62.910000
25%        NaN         NaN        NaN    2.000000     184.480000
50%        NaN         NaN        NaN    5.000000     279.120000
75%        NaN         NaN        NaN    6.000000     374.492500
max        NaN         NaN        NaN    8.000000     499.960000

Missing values

In [20]:
products=pd.read_csv("/products.csv")
prices=pd.read_csv("/competitor_prices.csv")
sales=pd.read_csv("/sales.csv")
products.isnull().sum()

product_id      0
product_name    0
category        0
brand           0
dtype: int64

In [21]:
products=pd.read_csv("/products.csv")
prices=pd.read_csv("/competitor_prices.csv")
sales=pd.read_csv("/sales.csv")
prices.isnull().sum()

date            0
product_id      0
platform        0
price           0
discount        0
stock_status    0
dtype: int64

In [22]:
products=pd.read_csv("/products.csv")
prices=pd.read_csv("/competitor_prices.csv")
sales=pd.read_csv("/sales.csv")
sales.isnull().sum()

sale_id          0
date             0
product_id       0
quantity         0
selling_price    0
dtype: int64

Duplicate records

In [26]:
products=pd.read_csv("/products.csv")
prices=pd.read_csv("/competitor_prices.csv")
sales=pd.read_csv("/sales.csv")
products.duplicated().sum()
prices.duplicated().sum()
sales.duplicated().sum()

np.int64(0)

Convert Date Columns

In [29]:
products=pd.read_csv("/products.csv")
prices=pd.read_csv("/competitor_prices.csv")
sales=pd.read_csv("/sales.csv")
prices["date"] = pd.to_datetime(prices["date"])
sales["date"] = pd.to_datetime(sales["date"])
sales.dtypes

sale_id                  object
date             datetime64[ns]
product_id               object
quantity                  int64
selling_price           float64
dtype: object

**Univariate Analysis**

products

In [31]:
products=pd.read_csv("/products.csv")
products["category"].value_counts()

category
Household        20
Grocery          20
Dairy            18
Snacks           17
Personal Care    14
Beverages        11
Name: count, dtype: int64

In [32]:
products=pd.read_csv("/products.csv")
products["brand"].value_counts()

brand
Surf Excel    20
ABC           20
Amul          18
Lays          17
Dove          14
Coca-Cola     11
Name: count, dtype: int64

prices

In [33]:
prices=pd.read_csv("/competitor_prices.csv")
prices["price"].min()

51.46

In [34]:
prices=pd.read_csv("/competitor_prices.csv")
prices["price"].max()

495.29

In [35]:
prices=pd.read_csv("/competitor_prices.csv")
prices["price"].mean()

np.float64(268.23420000000004)

In [36]:
prices=pd.read_csv("/competitor_prices.csv")
prices["platform"].value_counts()

platform
Amazon       25
Flipkart     25
Blinkit      25
BigBasket    25
Name: count, dtype: int64

In [37]:
prices=pd.read_csv("/competitor_prices.csv")
prices["stock_status"].value_counts()

stock_status
In Stock        53
Out of Stock    47
Name: count, dtype: int64

Sales

In [38]:
sales=pd.read_csv("/sales.csv")
sales["selling_price"].mean()

np.float64(282.71979999999996)

In [41]:
sales=pd.read_csv("/sales.csv")
sales["quantity"].sum()

np.int64(443)

**Merging table**

In [45]:
products=pd.read_csv("/products.csv")
prices=pd.read_csv("/competitor_prices.csv")
sales=pd.read_csv("/sales.csv")
prices_data=pd.merge(products,prices,on="product_id")
prices_data.head()

,product_id,product_name,category,brand,date,platform,price,discount,stock_status
0,P001,Household Item 1,Household,Surf Excel,2026-01-01,Amazon,495.29,20,In Stock
1,P002,Grocery Item 2,Grocery,ABC,2026-01-01,Flipkart,358.08,0,In Stock
2,P003,Grocery Item 3,Grocery,ABC,2026-01-01,Blinkit,419.81,10,Out of Stock
3,P004,Household Item 4,Household,Surf Excel,2026-01-01,BigBasket,170.48,5,Out of Stock
4,P005,Snacks Item 5,Snacks,Lays,2026-01-02,Amazon,145.68,15,Out of Stock

In [49]:
products=pd.read_csv("/products.csv")
prices=pd.read_csv("/competitor_prices.csv")
sales=pd.read_csv("/sales.csv")
prices_data=pd.merge(products,prices,on="product_id")
final_df = pd.merge(prices_data, sales, on="product_id")
final_df.head()

,product_id,product_name,category,brand,date_x,platform,price,discount,stock_status,sale_id,date_y,quantity,selling_price
0,P002,Grocery Item 2,Grocery,ABC,2026-01-01,Flipkart,358.08,0,In Stock,S066,2026-01-11,7,420.05
1,P002,Grocery Item 2,Grocery,ABC,2026-01-01,Flipkart,358.08,0,In Stock,S091,2026-01-10,3,173.44
2,P003,Grocery Item 3,Grocery,ABC,2026-01-01,Blinkit,419.81,10,Out of Stock,S055,2026-01-07,3,157.35
3,P005,Snacks Item 5,Snacks,Lays,2026-01-02,Amazon,145.68,15,Out of Stock,S005,2026-01-09,2,318.46
4,P006,Dairy Item 6,Dairy,Amul,2026-01-02,Flipkart,448.11,15,In Stock,S054,2026-01-21,1,477.33

In [50]:
final_df.shape

(100, 13)

**Feature Engineering**

revenue

In [51]:
final_df["revenue"]=final_df["quantity"]*final_df["selling_price"]
final_df.head()

,product_id,product_name,category,brand,date_x,platform,price,discount,stock_status,sale_id,date_y,quantity,selling_price,revenue
0,P002,Grocery Item 2,Grocery,ABC,2026-01-01,Flipkart,358.08,0,In Stock,S066,2026-01-11,7,420.05,2940.35
1,P002,Grocery Item 2,Grocery,ABC,2026-01-01,Flipkart,358.08,0,In Stock,S091,2026-01-10,3,173.44,520.32
2,P003,Grocery Item 3,Grocery,ABC,2026-01-01,Blinkit,419.81,10,Out of Stock,S055,2026-01-07,3,157.35,472.05
3,P005,Snacks Item 5,Snacks,Lays,2026-01-02,Amazon,145.68,15,Out of Stock,S005,2026-01-09,2,318.46,636.92
4,P006,Dairy Item 6,Dairy,Amul,2026-01-02,Flipkart,448.11,15,In Stock,S054,2026-01-21,1,477.33,477.33

saving

In [54]:
final_df["savings"]=final_df["price"]-final_df["selling_price"]
final_df.head()

,product_id,product_name,category,brand,date_x,platform,price,discount,stock_status,sale_id,date_y,quantity,selling_price,revenue,saving,savings
0,P002,Grocery Item 2,Grocery,ABC,2026-01-01,Flipkart,358.08,0,In Stock,S066,2026-01-11,7,420.05,2940.35,-61.97,-61.97
1,P002,Grocery Item 2,Grocery,ABC,2026-01-01,Flipkart,358.08,0,In Stock,S091,2026-01-10,3,173.44,520.32,184.64,184.64
2,P003,Grocery Item 3,Grocery,ABC,2026-01-01,Blinkit,419.81,10,Out of Stock,S055,2026-01-07,3,157.35,472.05,262.46,262.46
3,P005,Snacks Item 5,Snacks,Lays,2026-01-02,Amazon,145.68,15,Out of Stock,S005,2026-01-09,2,318.46,636.92,-172.78,-172.78
4,P006,Dairy Item 6,Dairy,Amul,2026-01-02,Flipkart,448.11,15,In Stock,S054,2026-01-21,1,477.33,477.33,-29.22,-29.22

Discount Amount

In [55]:
final_df["discount_amount"] = (final_df["price"] * final_df["discount"] / 100)
final_df.head()

,product_id,product_name,category,brand,date_x,platform,price,discount,stock_status,sale_id,date_y,quantity,selling_price,revenue,saving,savings,discount_amount
0,P002,Grocery Item 2,Grocery,ABC,2026-01-01,Flipkart,358.08,0,In Stock,S066,2026-01-11,7,420.05,2940.35,-61.97,-61.97,0.0000
1,P002,Grocery Item 2,Grocery,ABC,2026-01-01,Flipkart,358.08,0,In Stock,S091,2026-01-10,3,173.44,520.32,184.64,184.64,0.0000
2,P003,Grocery Item 3,Grocery,ABC,2026-01-01,Blinkit,419.81,10,Out of Stock,S055,2026-01-07,3,157.35,472.05,262.46,262.46,41.9810
3,P005,Snacks Item 5,Snacks,Lays,2026-01-02,Amazon,145.68,15,Out of Stock,S005,2026-01-09,2,318.46,636.92,-172.78,-172.78,21.8520
4,P006,Dairy Item 6,Dairy,Amul,2026-01-02,Flipkart,448.11,15,In Stock,S054,2026-01-21,1,477.33,477.33,-29.22,-29.22,67.2165

**Business Questions**



1.Which platform has the lowest average price?

In [56]:
prices.groupby("platform")["price"].mean().sort_values()

platform
Blinkit      230.3240
BigBasket    262.4668
Amazon       267.9780
Flipkart     312.1680
Name: price, dtype: float64

2.Which catagory has the highest revenue

In [57]:
final_df.groupby("category")["revenue"].sum().sort_values(ascending=False)

category
Snacks           31587.06
Household        25251.49
Dairy            18620.04
Grocery          17372.98
Personal Care    13359.66
Beverages        12822.24
Name: revenue, dtype: float64

3.Top
-selling products

In [58]:
final_df.groupby("product_name")["quantity"].sum().sort_values(ascending=False).head(10)

product_name
Dairy Item 74            23
Snacks Item 86           21
Personal Care Item 56    20
Household Item 67        17
Snacks Item 44           15
Snacks Item 49           15
Snacks Item 82           14
Dairy Item 71            14
Beverages Item 16        13
Snacks Item 35           11
Name: quantity, dtype: int64

4.Average discount by platform

In [61]:
prices.groupby("platform")["discount"].mean()

platform
Amazon       10.0
BigBasket    11.0
Blinkit      11.4
Flipkart      8.2
Name: discount, dtype: float64

5.Out-of-stock frequency

In [62]:
prices["stock_status"].value_counts()

stock_status
In Stock        53
Out of Stock    47
Name: count, dtype: int64

6.Average price by brand

In [18]:
products=pd.read_csv("/content/products.csv")
prices=pd.read_csv("/content/competitor_prices.csv")
sales=pd.read_csv("/content/sales.csv")
prices_data=pd.merge(products,prices,on="product_id")
final_df = pd.merge(prices_data, sales, on="product_id")
final_df.groupby("brand")["price"].mean()

brand
ABC           279.760588
Amul          207.143333
Coca-Cola     316.992727
Dove          211.323000
Lays          224.971250
Surf Excel    287.726522
Name: price, dtype: float64